---
title: "NetflixTitles"
author: "Jeff Grayum"
date: "5/21/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading libraries
```{r}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(ggthemes)
library(ggdark)
library(lubridate)
theme_set(theme_tufte())
theme_set(dark_theme_light())
library(tidytext)
library(snakecase)
library(tidylo)

```

Importing data.
```{r}
tuesdata <- tidytuesdayR::tt_load('2021-04-20')

netflix_titles <- tuesdata$netflix_titles %>%
  separate(duration, c("duration", "duration_units"), sep = " ", convert = TRUE ) %>%
  mutate(date_added = mdy(date_added),
         year_added = year(date_added))

netflix_titles %>%
  view()

netflix_titles %>%
  count(type)

netflix_titles %>%
  count(release_year)
```

Looking at ratio of movies/tv shows by decade.
```{r}
netflix_titles %>%
  ggplot(aes(release_year, fill = type)) +
  geom_histogram(binwidth = 5) +
  labs(x = "Release year",
       y = "",
       fill = NULL) +
  facet_wrap(~ type, ncol = 1, scales = "free_y") +
  theme(legend.position = "none")

netflix_titles %>%
  count(decade = 10 * (release_year %/% 10), type) %>%
  group_by(type) %>%
  mutate(percent = n / sum(n)) %>%
  ggplot(aes(decade, percent, color = type)) +
  geom_line()

summarize_titles <- function(tbl) {
  tbl %>%
    summarize(n = n(),
              median_durationb = median(duration),
              median_year = median(release_year)) %>%
    arrange(desc(n))
}

```

Comparing duration of movies over time.
```{r}
netflix_titles %>%
  filter(type == "Movie") %>%
  mutate(decade = 10 * (release_year %/% 10)) %>%
  ggplot(aes(decade, duration, group = decade)) +
  geom_boxplot() +
  labs(title = "Length of movies on Netflix",
       y = "Duration (mins)",
       x = "Decade released")
 
```

Lets look at categories.
```{r}
netflix_titles %>%
  separate_rows(listed_in, sep = "," ) %>%
  count(listed_in, sort = TRUE)

netflix_titles %>%
  separate_rows(listed_in, sep = ", " ) %>%
  group_by(type, genre = listed_in) %>%
  summarize(n = n(),
            median_duration = median(duration)) %>%
  arrange(desc(n)) %>%
  filter(type == "Movie") %>%
  filter(genre != "Movies") %>%
  mutate(genre = fct_reorder(genre, median_duration)) %>%
  ggplot(aes(median_duration, genre, fill = genre)) +
  geom_col() +
  labs(x = "Median duration",
       y = "Genre") +
  theme(legend.position = "none")

```

Date added.
```{r}
netflix_titles %>%
  filter(!is.na(date_added)) %>%
  arrange(date_added) %>%
  select(type, title, date_added)

netflix_titles %>%
  filter(!is.na(date_added)) %>%
  count(year_added = year(date_added))

netflix_titles %>%
  filter(!is.na(date_added)) %>%
  count(year_added, type) %>%
  ggplot(aes(year_added, n, fill = type)) +
  geom_area(alpha = 0.7) +
  labs(x = "Year added",
       y = "",
       fill = "", 
       title = "Titles added to Netflix each year")

netflix_titles %>%
  mutate(year_added = pmax(year_added, 2015)) %>%
  filter(!is.na(rating)) %>%
  count(year_added, rating = fct_lump(rating, 6)) %>%
  ggplot(aes(year_added, n, fill = rating)) +
  geom_area(alpha = 0.7) +
  labs(x = "Year added",
       y = "",
       fill = "", 
       title = "Titles added to Netflix each year")

netflix_titles %>%
  mutate(year_added = pmax(year_added, 2015)) %>%
  filter(!is.na(rating)) %>%
  group_by(type) %>%
  mutate(rating = fct_lump(rating, 4)) %>%
  count(year_added, rating = fct_lump(rating, 6)) %>%
  group_by(type, year_added) %>%
  mutate(percent = n / sum(n)) %>%
  ggplot(aes(year_added, percent, fill = rating)) +
  geom_area(alpha = 0.7) +
  facet_wrap(~ type) +
  labs(x = "Year added",
       y = "",
       fill = "", 
       title = "Titles added to Netflix each year") +
  scale_y_continuous(labels = percent)
```

Let's look at country.
```{r}
netflix_titles %>%
  filter(!is.na(country)) %>%
  count(country = fct_lump(country, 16),
        type,
        sort = TRUE) %>%
  mutate(country = fct_reorder(country, n)) %>%
  ggplot(aes(n, country, fill = type)) +
  geom_col() +
  labs(x = "# of titles added",
       y = "Contry",
       fill = "",
       title = "Number of titles added to Netflix by country")

netflix_titles %>%
  filter(!is.na(country)) %>%
  filter(type == "Movie") %>%
  group_by(country) %>%
  summarize_titles()

netflix_titles %>%
  filter(rating == "R") %>%
  count(country, sort = TRUE)

netflix_titles %>%
  filter(rating %in% c("R", "TV-MA")) %>%
  count(country, sort = TRUE)

netflix_titles %>%
  filter(!is.na(rating), !is.na(country)) %>%
  group_by(type, country = fct_lump(country, 9)) %>%
  summarize(n_mature = sum(rating %in% c("R", "TV-MA", "NC-17")),
            n = n(),
            .groups = "drop") %>%
  mutate(pct_mature = n_mature / n, 
         conf_low = qbeta(.025, n_mature + 0.5, n - n_mature + 0.5),
         conf_high = qbeta(0.975, n_mature + 0.5, n - n_mature +0.5)) %>%
  mutate(country = fct_reorder(country, n)) %>%
  ggplot(aes(pct_mature, country, color = type)) +
  geom_point(aes(size = n)) +
  geom_errorbar(aes(xmin = conf_low, xmax = conf_high)) +
  scale_x_continuous(labels = percent) +
  expand_limits(x = 0) +
  labs(x = "% Mature",
       y = "",
       title = "Which countries produce the most mature-rated Netflix content?")
  
```

```{r}
netflix_titles %>%
  filter(duration_units == "min") %>%
  mutate(country = fct_lump(country, 9)) %>%
  group_by(country) %>%
  summarize(mean_length = mean(duration)) %>%
  filter(country != "Other") %>%
  mutate(country = fct_reorder(country, mean_length)) %>%
  ggplot(aes(mean_length, country, fill = country)) +
  geom_col() +
  labs(x = "Avg length", 
       y = "",
       title = "Average length of Netflix titles by country") +
  theme(legend.position = "none")
  
netflix_titles %>%
  filter(duration_units == "min") %>%
  mutate(director = fct_lump(director, 9)) %>%
  group_by(director) %>%
  summarize(mean_length = mean(duration)) %>%
  filter(director != "Other") %>%
  mutate(director = fct_reorder(director, mean_length)) %>%
  ggplot(aes(mean_length, director, fill = director)) +
  geom_col() +
  labs(x = "Avg length", 
       y = "",
       title = "Average length of Netflix titles by most popular directors") +
  theme(legend.position = "none")  

  #mutate(mean_rating = fct_reorder(mean_rating, n)) %>% 
  ggplot(aes(mean_rating, director)) +
  geom_col()
```

Can we predict rating?
```{r}
words_unnested <- netflix_titles %>%
  unnest_tokens(word, description) %>%
  anti_join(stop_words, by = "word") 

words_unnested %>%
  count(type, word, sort = TRUE) %>%
  mutate(type = to_snake_case(type)) %>%
  spread(type, n, fill = 0) %>%
  mutate(total = movie + tv_show) %>%
  arrange(desc(total)) %>%
  head(100) %>%
  ggplot(aes(movie, tv_show)) +
  geom_point() +
  geom_text(aes(label = word), vjust = 1, hjust = 1) +
  scale_x_log10() +
  scale_y_log10()
           

words_unnested %>%
  count(type, word) %>%
  bind_log_odds(type, word, n) %>%
  arrange(desc(log_odds_weighted)) %>%
  group_by(type) %>%
  top_n(10, log_odds_weighted) %>%
  ungroup() %>%
  mutate(word = fct_reorder(word, log_odds_weighted)) %>%
  ggplot(aes(log_odds_weighted, word)) +
  geom_col() +
  facet_wrap(~type, scales = "free_y") +
  labs(x = "Log odds weighted",
       y = "Word",
       title = "What words are most overrepresented in Netflix titles and descriptions?")
  
```

